### ISSUE TITLE
Supports Gnome 42

### ISSUE THREAD

**Issue by stdevPavelmc** [duonggiakhanhb/Cloudflare_GNOME_Extension#1]
Latest Suse and Fedora adopted Gnome 42, and Ubuntu jammy is packing 42 also for the release at the end of the next month.

I installed it on the dev version of Ubuntu Jammy and it does not work.

**Comment by stdevPavelmc** [comment]
Any progress?

**Comment by duonggiakhanhb** [comment]
I have updated in the new commit
